# Generated by Django 5.1.3 on 2026-06-30 20:44

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_user_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='advance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery (Full)'), ('advance_easypaisa', '50% Advance via EasyPaisa/JazzCash'), ('advance_bank', '50% Advance via Bank Transfer')], default='cod', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_receipt',
            field=models.ImageField(blank=True, null=True, upload_to=apps.orders.models.payment_receipt_path),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('received', 'Amount Received - Not Verified'), ('verified', 'Verified & Processing')], default='pending', max_length=20),
        ),
    ]
