# Generated by Django 5.1.3 on 2026-06-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hex_code', models.CharField(default='#000000', help_text='e.g. #800020', max_length=7)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'colors',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
