# Generated by Django 5.1.3 on 2026-07-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_review_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_coming_soon',
            field=models.BooleanField(default=False),
        ),
    ]
