# Generated by Django 5.1.3 on 2026-07-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_add_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='attribute_definitions',
            field=models.JSONField(blank=True, default=list, help_text='Form field definitions for products in this category'),
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Category-specific attributes'),
        ),
    ]
